const actions = {
  REGISTER_GUEST : "REGISTER_GUEST",
  CURRENT_GUEST : "CURRENT_GUEST",
  COUNTRIES: "COUNTRIES",
  DOCUMENTS: "DOCUMENTS",
  HOTELS: "HOTELS",
  ROOMS: "ROOMS",
  SELECTED_INFO: "SELECTED_INFO",
  ROOM_DETAIL: "ROOM_DETAIL",
  SELECTED_ROOMS: "SELECTED_ROOMS",
  LIST_CAR: "LIST_CAR"
}
export default actions;
